export { PLAYER_MOVEMENTS, SHAPE_DELAY, SHAPES, TRIANGULO, CUADRADO, ROMBO, CRUZ, TIME_DELAY, POINTS_PERCENTAGE, POINTS_PERCENTAGE_VALUE_START};
//crear enumeracion
const PLAYER_MOVEMENTS = {
    x: 250 ,
    y: 350 ,
}

const SHAPE_DELAY = 2500;
const TIME_DELAY = 1000;
const TRIANGULO = "Triangulo";
const CUADRADO = "Cuadrado";
const ROMBO = "Rombo";
const CRUZ = "Cruz"; 

const SHAPES = [TRIANGULO, CUADRADO, ROMBO, CRUZ];
const POINTS_PERCENTAGE = "value";
const POINTS_PERCENTAGE_VALUE_START = 1;


